config/routes.rb
Chronuscop::Application.routes.draw do

  resources :languages

  devise_for :users

  get "pages/index"

  get "pages/about"

  get "pages/contact"

  get "pages/help"

  resources :projects do
    member do                   # Action to add a language to a project.
      get 'addlanguage'
    end

    resources :translations do
      collection do
        get 'manage'
      end

      collection do
        post 'add'              # Added to enable posting translations, all at once.
      end
    end
  end

  root :to => "pages#index"

end

app/models/translation.rb
class Translation < ActiveRecord::Base
  attr_accessible :key
  attr_accessible :value

  belongs_to :projects
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_filter :authenticate_user!


  def index
    @project = Project.find(params[:project_id])

    # Handling the case when only translations updated after last sync are needed.
    # last_update_at is an optional parameter.
    last_update_at = params[:last_update_at]

    # if the last_update_at parameter is passed then use it.
    if (last_update_at) then
      last_update_at = last_update_at.to_i
      time_obj = Time.at(last_update_at)
      @translations = @project.translations.where("updated_at > ?",time_obj)
    else
      @translations = @project.translations
    end


    respond_to do |format|
      format.html
      format.xml { render :xml => @translations }
    end
  end

  def manage                    # Action to manage translations.
    @project = Project.find(params[:project_id])

    if(!params[:language])
      flash[:error] = "No language parameter passed."
      redirect_to project_path(@project)
    else
      @default_translations = @project.translations.where("language = ?",0)
      # @language_hash = Hash.new
      # @project.translations.where("language = ?",params[:language]).each do |t|
      #   @language_hash[t.key] = t.value

    end
  end

  def create
    @project = Project.find(params[:project_id])
    @translation = @project.translations.build(params[:translation])

    if(@translation.save)
      respond_to do |format|
        format.html { redirect_to :back, :flash => { :success => "Translation saved."} }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to :back, :flash => { :error => "Could not save translation.."} }
        format.js
      end
    end
  end

  def new
    @project = Project.find(params[:project_id])
    @translation = @project.translations.build()
  end

  def add                       # Action to add or update default translations.
    if(params[:translations_xml_string] == nil) then
      puts "Translations parameter missing."
    else
      require 'xmlsimple'
      translations_hash = XmlSimple.xml_in(params[:translations_xml_string])
      @project = Project.find(params[:project_id])

      translations_hash.each do |key,value|

        # Handling the default translations.
        t = Translation.find_by_key(key)
        if ( t ) then
          t.value = value
          t.save
        else

          @translation = @project.translations.build()
          @translation.key = key
          @translation.value = value
          @translation.language = 0 # 0 is the code for default.
          if ! @translation.save then
            puts "record could not be saved."
          end
        end

        # Handling the english translations that will be added.
        en_key = key.sub(/default/,"en")
        t2 = Translation.find_by_key(en_key)

        # If there is no such key then add it. If there is one
        # then don't touch it.
        if( ! t2 ) then
          @en_translation = @project.translations.build()
          @en_translation.key = en_key
          @en_translation.value = value
          @en_translation.language = 1 # 1 is the language code for english

          if ! @en_translation.save then
            puts "record could not be saved."
          end
        end
      end

    end
  end

  def edit
    @project = Project.find(params[:project_id])
    @translation = @project.translations.build(params[:translation])

    if(@translation.save)
      redirect_to :back, :flash => { :success => "Translation saved."}
    else
      redirect_to :back, :flash => { :error => "Could not save"}
    end
  end

  def show
  end

  # responds to PUT
  def update
    @translation = Translation.find(params[:id])

    if(@translation.update_attributes(params[:translation])) then
      respond_to do |format|
        format.html { redirect_to :back, :flash => { :success => "Updated tranlation."} }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to :back, :flash => { :success => "Could not update translation."} }
        format.js
      end
    end
  end

  def destroy
  end

end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/translations/add.html.erb
<h1>Add Translation page.</h1>
<p> Please verify the addition of translations in the chronuscop website.</p>

app/views/translations/create.html.erb
<h1>Translations#create</h1>
<p>Find me in app/views/translations/create.html.erb</p>

app/views/translations/create.js.erb
$("message").update("worked !!")

app/views/translations/destroy.html.erb
<h1>Translations#destroy</h1>
<p>Find me in app/views/translations/destroy.html.erb</p>

app/views/translations/edit.html.erb
<h1>Translations#edit</h1>
<p>Find me in app/views/translations/edit.html.erb</p>

app/views/translations/index.html.erb
<h1 class="heading">Translations list</h1>
<br>
<hr>
<div id="translations">
<% if @translations.count > 0 %>
  <table>
    <tr>
      <td class="heading">Key</td>
      <td class="heading">Value</td>
    </tr>
    <% @translations.each do |t| %>
      <tr>
        <td><%= t.key %></td>
        <td><%= t.value %></td>
      </tr>
    <% end %>
  </table>
<hr>
<% end %>

<%= form_for(:translation, @translation, :url => project_translations_path) do |f| %>
<table>
  <tr>
    <td><%= f.label :key %></td>
    <td><%= f.text_field :key %></td>
  </tr>
  <tr>
    <td> <%= f.label :value %></td>
    <td> <%= f.text_field :value %></td>
  </tr>
</table>
</div>
  <div class="actions">
    <%= f.submit "Add" %>
  </div>
<% end %>

app/views/translations/manage.html.erb
<!-- Capturing the language that is passed as a parameter. -->
<% language = Language.find_by_id(params[:language]) %>

<h2>Manage your <%= language.name %> translations</h2>
<hr>
<b><%= link_to "Project",@project %></b><br/><hr>

<!-- Displaying default text followed by a form. -->
<% @default_translations.each do |d|
     corr_language_key = d.key.sub(/default/,language.code) %>
<%= d.value %><br/>

<%     # check whether there is already a translation corresponding to this key in this project.
       @corr_translation = @project.translations.find_by_key(corr_language_key) %>

<!-- If there is no such translation then create a new one but do not save it to db. -->
<%
     if(!@corr_translation) then
       @corr_translation = @project.translations.build()
       @corr_translation.key = corr_language_key
       @corr_translation.language = language.id
     end
%>

<div id="message<%= @corr_translation.id %>">
</div>
<!-- A form is displayed. -->
<%= form_for [@project,@corr_translation],:remote => true  do |f| %>
  <div class="field">
    <%= f.label :value %><br/>
    <%= f.text_field :value %>
  </div><br/>
  <%= f.hidden_field(:key)%>
  <%= f.hidden_field(:language) %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% end %>

app/views/translations/new.html.erb
<h1>Translations#new</h1>

<%= form_for(:translation, @translation, :url => project_translations_path) do |f| %>
  <div class="field">
    <%= f.label :key %>:
    <%= f.text_field :key %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :value %>:
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit "Add" %>
  </div>
<% end %>

app/views/translations/show.html.erb
<h1>Translations#show</h1>
<p>Find me in app/views/translations/show.html.erb</p>

app/views/translations/update.html.erb
<h1>Translations#update</h1>
<p>Find me in app/views/translations/update.html.erb</p>

app/views/translations/update.js.erb
<% id = @translation.id %>
$("message<%= id %>").update("Updated.")