config/routes.rb
Chronuscop::Application.routes.draw do

  resources :languages

  devise_for :users

  get "pages/index"

  get "pages/about"

  get "pages/contact"

  get "pages/help"

  resources :projects do
    member do                   # Action to add a language to a project.
      get 'addlanguage'
    end

    resources :translations do
      collection do
        get 'manage'
      end

      collection do
        post 'add'              # Added to enable posting translations, all at once.
      end
    end
  end

  root :to => "pages#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name

  belongs_to :user
  has_many :translations, :dependent => :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!


  def index
  end

  def create
    @project = current_user.projects.build(params[:project])
    if( @project.save) then
      redirect_to projects_path, :flash => {:success => "Successfully added project"}
    else
      render 'new'
    end
  end

  def new
    @project = Project.new      # necessary to use form_for
  end

  def edit
  end

  def show
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html
      format.xml { render :xml => @project.translations } # required to use a xml-parser-client.
    end
  end

  def addlanguage               # Action to add a language.
    @project = Project.find(params[:id])

    # Checking for the presence and validity of the parameter :language
    if(! params[:language]) then
      flash[:error] = "No parameter :language"
      redirect_to projects_path(@project)
    end

    # Adding language.
    if(! @project.languages) then
      @project.languages = params[:language].to_s
      @project.save
      flash[:success] = "Added language."
      redirect_to project_path(@project)
      return
    else
      arr = @project.languages.split(/:/)

      if(arr.include?(params[:language].to_s)) then
        flash[:notice] = "Language is already added."
        redirect_to project_path(@project)
        return
      else
        @project.languages = @project.languages + ":" + params[:language].to_s
        @project.save
        flash[:success] = "Successfully added language."
        redirect_to project_path(@project)
        return
      end
    end

  end

  def update
  end

  def destroy
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h1 class="heading">Projects</h1>
<p> Manage your projects. </p>
<hr>

<h3>
  <% if( current_user.projects.count == 0) then %>
  <p> No user projects. </p>
<% else %>

  <ol>
    <% current_user.projects.each do |p| %>
      <li><%= link_to "#{p.name}",p %></li>
    <% end %>
  </ol>
<% end %>
<%= link_to "Add project",new_project_path %>
</h3>

app/views/projects/new.html.erb
<h1>Add a project.</h1>

<%= form_for(@project) do |f| %>
<div class="field">
  <%= f.label :name %><br/>
  <%= f.text_field :name %>
</div>
<%= f.submit "Add" %>
<% end %>

app/views/projects/show.html.erb
<h1 class="heading"><%= @project.name %></h1>
<hr>
<%= form_tag(manage_project_translations_path(@project), :method => "get") do %>
  <%= label_tag(:language, "Choose language") %><br/>

  <% options_array = Array.new %>
  <% langs_arr = @project.languages.split(/:/) %>
  <% for i in 0..(langs_arr.size-1) do %>
  <%  options_array[i] = [Language.find_by_id(langs_arr[i]).name,langs_arr[i]] %>
  <% end %>
  <%= select_tag(:language,options_for_select(options_array)) %>
  <%= submit_tag("Manage") %>
<% end %>

<br/>
<%= form_tag(addlanguage_project_path(@project), :method => "get") do %>
  <%= label_tag(:language, "Add language")%><br/>
  <%= select_tag(:language,options_from_collection_for_select(Language.all, :id, :name)) %>
  <%= submit_tag("Add") %>
<% end %>
<hr>
<% if(@project.translations.count == 0) then %>
<%= "No translations added yet" %><br/>
<% else %>

<h3>All translations in this project.</h3>
<div id="translations">
  <table border="1">
    <tr>
      <td class="heading"><b>key</b></td>
      <td class="heading"><b>value</b></td>
    </tr>
    <% @project.translations.each do |t| %>
      <tr>
        <td><%= t.key %></td>
        <td><%= t.value %></td>
      </tr>
    <% end %>
  </table>
</div>
<% end %>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>