config/routes.rb
Chronuscop::Application.routes.draw do

  resources :languages

  devise_for :users

  get "pages/index"

  get "pages/about"

  get "pages/contact"

  get "pages/help"

  resources :projects do
    member do                   # Action to add a language to a project.
      get 'addlanguage'
    end

    resources :translations do
      collection do
        get 'manage'
      end

      collection do
        post 'add'              # Added to enable posting translations, all at once.
      end
    end
  end

  root :to => "pages#index"

end

app/views/layouts/_banner.html.erb
<%= image_tag('chronus.png') %>Chronuscop

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", pages_about_path %></li>
      <li><%= link_to "Contact", pages_contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if user_signed_in? then %>
	<li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Help", pages_help_path %></li>
      <% if user_signed_in? %>
	<li><%= link_to "Sign out", destroy_user_session_path %></li>
      <% else %>
	<li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "Chronuscop" %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
    <div id="banner">
      <%= render 'layouts/banner' %>
    </div>

    <div class="container">
      <%= render 'layouts/header' %>
      <br/>
      <section>
        <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>